// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: light_needs.sql

package database

import (
	"context"
)

const resetLightNeedsTable = `-- name: ResetLightNeedsTable :exec
delete from light_needs
`

func (q *Queries) ResetLightNeedsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetLightNeedsTable)
	return err
}
