// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Biome struct {
	ID             uuid.UUID       `json:"id"`
	CreatedAt      time.Time       `json:"createdAt"`
	UpdatedAt      time.Time       `json:"updatedAt"`
	DeletedAt      sql.NullTime    `json:"deletedAt"`
	CreatedBy      string          `json:"createdBy"`
	UpdatedBy      string          `json:"updatedBy"`
	DeletedBy      sql.NullString  `json:"deletedBy"`
	KoppenClass    string          `json:"koppenClass"`
	AvgSummerTempC sql.NullFloat64 `json:"avgSummerTempC"`
	AvgWinterTempC sql.NullFloat64 `json:"avgWinterTempC"`
	AvgSummerHumid sql.NullFloat64 `json:"avgSummerHumid"`
	AvgWinterHumid sql.NullFloat64 `json:"avgWinterHumid"`
	AnnualRainMm   sql.NullInt32   `json:"annualRainMm"`
	AnnualSunHours sql.NullInt32   `json:"annualSunHours"`
}

type Plant struct {
	ID               uuid.UUID      `json:"id"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
	DeletedAt        sql.NullTime   `json:"deletedAt"`
	CreatedBy        string         `json:"createdBy"`
	UpdatedBy        string         `json:"updatedBy"`
	DeletedBy        sql.NullString `json:"deletedBy"`
	BiomeID          uuid.NullUUID  `json:"biomeId"`
	SpeciesName      string         `json:"speciesName"`
	HumanPoisonToxic sql.NullBool   `json:"humanPoisonToxic"`
	PetPoisonToxic   sql.NullBool   `json:"petPoisonToxic"`
	HumanEdible      sql.NullBool   `json:"humanEdible"`
	PetEdible        sql.NullBool   `json:"petEdible"`
}

type PlantName struct {
	ID         uuid.UUID      `json:"id"`
	CreatedAt  time.Time      `json:"createdAt"`
	UpdatedAt  time.Time      `json:"updatedAt"`
	DeletedAt  sql.NullTime   `json:"deletedAt"`
	CreatedBy  string         `json:"createdBy"`
	UpdatedBy  string         `json:"updatedBy"`
	DeletedBy  sql.NullString `json:"deletedBy"`
	PlantID    uuid.NullUUID  `json:"plantId"`
	LangCode   sql.NullString `json:"langCode"`
	CommonName sql.NullString `json:"commonName"`
}

type RefreshToken struct {
	RefreshToken string         `json:"refreshToken"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
	DeletedAt    sql.NullTime   `json:"deletedAt"`
	CreatedBy    string         `json:"createdBy"`
	UpdatedBy    string         `json:"updatedBy"`
	DeletedBy    sql.NullString `json:"deletedBy"`
	RevokedAt    sql.NullTime   `json:"revokedAt"`
	RevokedBy    sql.NullString `json:"revokedBy"`
	ExpiresAt    time.Time      `json:"expiresAt"`
	UserID       uuid.UUID      `json:"userId"`
}

type User struct {
	ID             uuid.UUID      `json:"id"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	DeletedAt      sql.NullTime   `json:"deletedAt"`
	CreatedBy      string         `json:"createdBy"`
	UpdatedBy      string         `json:"updatedBy"`
	DeletedBy      sql.NullString `json:"deletedBy"`
	JoinDate       time.Time      `json:"joinDate"`
	IsAdmin        bool           `json:"isAdmin"`
	Email          string         `json:"email"`
	HashedPassword string         `json:"hashedPassword"`
}

type UsersPlant struct {
	ID           uuid.UUID      `json:"id"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
	DeletedAt    sql.NullTime   `json:"deletedAt"`
	CreatedBy    string         `json:"createdBy"`
	UpdatedBy    string         `json:"updatedBy"`
	DeletedBy    sql.NullString `json:"deletedBy"`
	PlantID      uuid.NullUUID  `json:"plantId"`
	UserID       uuid.NullUUID  `json:"userId"`
	AdoptionDate sql.NullTime   `json:"adoptionDate"`
	Name         sql.NullString `json:"name"`
}
