// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Biome struct {
	ID             uuid.UUID
	KoppenClass    string
	AvgSummerTempC sql.NullFloat64
	AvgWinterTempC sql.NullFloat64
	AvgSummerHumid sql.NullFloat64
	AvgWinterHumid sql.NullFloat64
	AnnualRainMm   sql.NullInt32
	AnnualSunHours sql.NullInt32
}

type Plant struct {
	ID                  uuid.UUID
	BiomeID             uuid.NullUUID
	RoomID              uuid.NullUUID
	WaterScheduleID     uuid.NullUUID
	SpeciesName         string
	PetToxic            sql.NullBool
	HumanToxic          sql.NullBool
	HumanEdible         sql.NullBool
	AvgIdealTempC       float64
	AvgIdealHumid       sql.NullFloat64
	IdealLightHours     sql.NullFloat64
	IdealLightIntensity sql.NullString
}
