// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type LightNeed struct {
	ID          uuid.UUID     `json:"id"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdatedAt   time.Time     `json:"updatedAt"`
	DeletedAt   sql.NullTime  `json:"deletedAt"`
	CreatedBy   uuid.UUID     `json:"createdBy"`
	UpdatedBy   uuid.UUID     `json:"updatedBy"`
	DeletedBy   uuid.NullUUID `json:"deletedBy"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
}

type PlantName struct {
	ID         uuid.UUID     `json:"id"`
	CreatedAt  time.Time     `json:"createdAt"`
	UpdatedAt  time.Time     `json:"updatedAt"`
	DeletedAt  sql.NullTime  `json:"deletedAt"`
	CreatedBy  uuid.UUID     `json:"createdBy"`
	UpdatedBy  uuid.UUID     `json:"updatedBy"`
	DeletedBy  uuid.NullUUID `json:"deletedBy"`
	PlantID    uuid.UUID     `json:"plantId"`
	LangCode   string        `json:"langCode"`
	CommonName string        `json:"commonName"`
}

type PlantSpecy struct {
	ID               uuid.UUID     `json:"id"`
	CreatedAt        time.Time     `json:"createdAt"`
	UpdatedAt        time.Time     `json:"updatedAt"`
	DeletedAt        sql.NullTime  `json:"deletedAt"`
	CreatedBy        uuid.UUID     `json:"createdBy"`
	UpdatedBy        uuid.UUID     `json:"updatedBy"`
	DeletedBy        uuid.NullUUID `json:"deletedBy"`
	SpeciesName      string        `json:"speciesName"`
	HumanPoisonToxic sql.NullBool  `json:"humanPoisonToxic"`
	PetPoisonToxic   sql.NullBool  `json:"petPoisonToxic"`
	HumanEdible      sql.NullBool  `json:"humanEdible"`
	PetEdible        sql.NullBool  `json:"petEdible"`
	PlantTypeID      uuid.NullUUID `json:"plantTypeId"`
	LightNeedsID     uuid.NullUUID `json:"lightNeedsId"`
	WateringNeedsID  uuid.NullUUID `json:"wateringNeedsId"`
}

type PlantType struct {
	ID                    uuid.UUID       `json:"id"`
	CreatedAt             time.Time       `json:"createdAt"`
	UpdatedAt             time.Time       `json:"updatedAt"`
	DeletedAt             sql.NullTime    `json:"deletedAt"`
	CreatedBy             uuid.UUID       `json:"createdBy"`
	UpdatedBy             uuid.UUID       `json:"updatedBy"`
	DeletedBy             uuid.NullUUID   `json:"deletedBy"`
	Name                  string          `json:"name"`
	Description           string          `json:"description"`
	MaxTemperatureCelsius sql.NullFloat64 `json:"maxTemperatureCelsius"`
	MinTemperatureCelsius sql.NullFloat64 `json:"minTemperatureCelsius"`
	MaxHumidityPercent    sql.NullFloat64 `json:"maxHumidityPercent"`
	MinHumidityPercent    sql.NullFloat64 `json:"minHumidityPercent"`
	SoilOrganicMix        sql.NullString  `json:"soilOrganicMix"`
	SoilGritMix           sql.NullString  `json:"soilGritMix"`
	SoilDrainageMix       sql.NullString  `json:"soilDrainageMix"`
}

type RefreshToken struct {
	RefreshToken string        `json:"refreshToken"`
	CreatedAt    time.Time     `json:"createdAt"`
	UpdatedAt    time.Time     `json:"updatedAt"`
	DeletedAt    sql.NullTime  `json:"deletedAt"`
	CreatedBy    uuid.UUID     `json:"createdBy"`
	UpdatedBy    uuid.UUID     `json:"updatedBy"`
	DeletedBy    uuid.NullUUID `json:"deletedBy"`
	RevokedAt    sql.NullTime  `json:"revokedAt"`
	RevokedBy    uuid.NullUUID `json:"revokedBy"`
	ExpiresAt    time.Time     `json:"expiresAt"`
	UserID       uuid.UUID     `json:"userId"`
}

type User struct {
	ID             uuid.UUID     `json:"id"`
	CreatedAt      time.Time     `json:"createdAt"`
	UpdatedAt      time.Time     `json:"updatedAt"`
	DeletedAt      sql.NullTime  `json:"deletedAt"`
	CreatedBy      uuid.UUID     `json:"createdBy"`
	UpdatedBy      uuid.UUID     `json:"updatedBy"`
	DeletedBy      uuid.NullUUID `json:"deletedBy"`
	JoinDate       time.Time     `json:"joinDate"`
	IsAdmin        bool          `json:"isAdmin"`
	Email          string        `json:"email"`
	HashedPassword string        `json:"hashedPassword"`
}

type UsersPlant struct {
	ID           uuid.UUID      `json:"id"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
	DeletedAt    sql.NullTime   `json:"deletedAt"`
	CreatedBy    uuid.UUID      `json:"createdBy"`
	UpdatedBy    uuid.UUID      `json:"updatedBy"`
	DeletedBy    uuid.NullUUID  `json:"deletedBy"`
	PlantID      uuid.UUID      `json:"plantId"`
	UserID       uuid.UUID      `json:"userId"`
	AdoptionDate sql.NullTime   `json:"adoptionDate"`
	Name         sql.NullString `json:"name"`
}

type WateringNeed struct {
	ID               uuid.UUID     `json:"id"`
	CreatedAt        time.Time     `json:"createdAt"`
	UpdatedAt        time.Time     `json:"updatedAt"`
	DeletedAt        sql.NullTime  `json:"deletedAt"`
	CreatedBy        uuid.UUID     `json:"createdBy"`
	UpdatedBy        uuid.UUID     `json:"updatedBy"`
	DeletedBy        uuid.NullUUID `json:"deletedBy"`
	WateringType     string        `json:"wateringType"`
	Description      string        `json:"description"`
	GrowSeason       float64       `json:"growSeason"`
	TransitionSeason float64       `json:"transitionSeason"`
	DormantSeason    float64       `json:"dormantSeason"`
}
