// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: plant_types.sql

package database

import (
	"context"
)

const resetPlantTypesTable = `-- name: ResetPlantTypesTable :exec
delete from plant_types
`

func (q *Queries) ResetPlantTypesTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetPlantTypesTable)
	return err
}
