// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: plant_names.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPlantName = `-- name: CreatePlantName :one
insert into plant_names (
	id,
  created_at, updated_at,
	created_by, updated_by,
  plant_id,
  lang_code,
  common_name
) values (
  gen_random_uuid(),
  now(), now(),
  $1, $1,
  $2,
  $3,
  $4
) returning id, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by, plant_id, lang_code, common_name
`

type CreatePlantNameParams struct {
	CreatedBy  uuid.UUID      `json:"createdBy"`
	PlantID    uuid.NullUUID  `json:"plantId"`
	LangCode   sql.NullString `json:"langCode"`
	CommonName sql.NullString `json:"commonName"`
}

func (q *Queries) CreatePlantName(ctx context.Context, arg CreatePlantNameParams) (PlantName, error) {
	row := q.db.QueryRowContext(ctx, createPlantName,
		arg.CreatedBy,
		arg.PlantID,
		arg.LangCode,
		arg.CommonName,
	)
	var i PlantName
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.PlantID,
		&i.LangCode,
		&i.CommonName,
	)
	return i, err
}

const markPlantNameAsDeletedByID = `-- name: MarkPlantNameAsDeletedByID :exec
update plant_names
  set
  deleted_at = now(),
  deleted_by = $2
where id = $1
`

type MarkPlantNameAsDeletedByIDParams struct {
	ID        uuid.UUID     `json:"id"`
	DeletedBy uuid.NullUUID `json:"deletedBy"`
}

func (q *Queries) MarkPlantNameAsDeletedByID(ctx context.Context, arg MarkPlantNameAsDeletedByIDParams) error {
	_, err := q.db.ExecContext(ctx, markPlantNameAsDeletedByID, arg.ID, arg.DeletedBy)
	return err
}

const resetPlantNamesTable = `-- name: ResetPlantNamesTable :exec
delete from plant_names
`

func (q *Queries) ResetPlantNamesTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetPlantNamesTable)
	return err
}
