// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: watering_needs.sql

package database

import (
	"context"
)

const resetWaterNeedsTable = `-- name: ResetWaterNeedsTable :exec
delete from water_needs
`

func (q *Queries) ResetWaterNeedsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetWaterNeedsTable)
	return err
}
