// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: watering_needs.sql

package database

import (
	"context"
)

const resetWateringNeedsTable = `-- name: ResetWateringNeedsTable :exec
delete from watering_needs
`

func (q *Queries) ResetWateringNeedsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetWateringNeedsTable)
	return err
}
