openapi: 3.1.0

info:
  title: Plantae
  description: Plant Care Database
  version: 0.1.0

paths:
  /api/v1/health:
    $ref: "./paths/health.yaml"
  /api/v1/createUser:
    $ref: "./paths/createUser.yaml"
  /api/v1/loginUser:
    $ref: "./paths/loginUser.yaml"

components:
  schemas:
    CreateUserRequest:
      $ref: "./components/schemas/CreateUserRequest.yaml"
    CreateUserResponse:
      $ref: "./components/schemas/CreateUserResponse.yaml"
    LoginUserRequest:
      $ref: "./components/schemas/LoginUserRequest.yaml"
    LoginUserResponse:
      $ref: "./components/schemas/LoginUserResponse.yaml"
    ErrorResponse:
      $ref: "./components/schemas/ErrorResponse.yaml"
